# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-04 13:05
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181204_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='/static/img/article/default.jpg'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='img',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='/static/img/carousel/default.jpg', max_length=200, verbose_name='轮播图片'),
        ),
    ]
